# Generated by Django 5.2.7 on 2025-11-01 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('pronouns', models.CharField(blank=True, max_length=20)),
                ('position', models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], max_length=30)),
                ('shirt_number', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_committee', models.BooleanField(default=False)),
                ('committee_role', models.CharField(blank=True, max_length=100)),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='headshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.team')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
