# Generated by Django 5.2.7 on 2025-11-01 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='primary_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='api.team'),
        ),
    ]
