# Generated by Django 5.2.7 on 2025-11-03 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_player_primary_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('team_against', models.CharField(max_length=100)),
                ('competition', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('home_match', models.BooleanField(default=True)),
                ('match_completed', models.BooleanField(default=False)),
                ('home_team_score', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('away_team_score', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.team')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
